spring:
  datasource:
    username: root
    password: 2365
    url: jdbc:mysql://localhost:3306/personnel?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  type-aliases-package: com.wll
  #dao-locations: classpath*:com/hxgj168/central/*/dao/dao/*Mapper.xml,classpath*:com/hxgj168/central/*/*/dao/dao/*Mapper.xml,classpath*:com/hxgj168/central/*/*/*/dao/dao/*Mapper.xml,classpath*:com/hxgj168/central/*/*/*/*/dao/dao/*Mapper.xml
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  config-location:

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
